# Webhook signature verification and event parsing.
#
# The HMAC scheme is ported from salt-call-agent-example/webhook_auth.py
# (`X-Salt-Signature: t=<unix>,v1=<hex>`, HMAC-SHA256(secret, f"{t}.{raw}")
# over the EXACT raw bytes salt-api sent, 300s default replay tolerance) --
# proven byte-compatible with salt-agent-sdk's own verification code
# (dist/webhook.js's `rejectionReason`) by tests/fixtures/webhook_signature_vector.json,
# generated by running real signed requests through the compiled TS SDK
# (see scripts/generate_ts_vector.cjs).
#
# `handle()` is the framework-neutral entry point: headers + raw body in,
# a parsed, signature-checked Event out. `saltapp.agent.Agent` builds on
# it for both webhook (ASGI) and socket-mode delivery, so the mention rule
# and loop guards in agent.py see identical Event shapes regardless of
# transport.
from __future__ import annotations

import hashlib
import hmac
import json
import logging
import re
import time
from dataclasses import dataclass, field
from typing import Any, Mapping

from saltapp.errors import SaltAppError

_logger = logging.getLogger("saltapp.webhook")

SIGNATURE_HEADER = "X-Salt-Signature"
AGENT_ID_HEADER = "X-Salt-Agent-Id"
DELIVERY_ID_HEADER = "X-Salt-Delivery-Id"

DEFAULT_TOLERANCE_SECONDS = 300

EventType = str  # "message" | "card_interaction" | "invoice_paid" | "chat_opened" | "handoff_confirmed" | "handoff_received" | "unknown"


class WebhookVerificationError(SaltAppError):
    """An inbound webhook/socket-update envelope failed signature or
    replay-window verification."""


def _get_header(headers: Mapping[str, Any], name: str) -> str | None:
    """Case-insensitive header lookup that works for a plain dict, an
    httpx.Headers, a WSGI/ASGI-adapted mapping, or anything else that
    behaves like Mapping[str, str]."""
    if name in headers:
        return headers[name]
    lname = name.lower()
    for key, value in headers.items():
        if key.lower() == lname:
            return value
    return None


def parse_signature_header(header_value: str) -> tuple[int, str]:
    """Parse `t=<unix>,v1=<hex>` into (timestamp, hex_digest)."""
    parts: dict[str, str] = {}
    for chunk in header_value.split(","):
        key, sep, value = chunk.partition("=")
        if sep:
            parts[key.strip()] = value.strip()
    if "t" not in parts or "v1" not in parts:
        raise WebhookVerificationError(f"malformed {SIGNATURE_HEADER} header: {header_value!r}")
    try:
        timestamp = int(parts["t"])
    except ValueError as exc:
        raise WebhookVerificationError(f"non-integer timestamp in {SIGNATURE_HEADER}: {parts['t']!r}") from exc
    return timestamp, parts["v1"]


def verify_signature(
    raw_body: bytes,
    signature_header: str | None,
    secret: str | None,
    *,
    tolerance_seconds: int = DEFAULT_TOLERANCE_SECONDS,
    now: float | None = None,
) -> None:
    """Verify `X-Salt-Signature: t=<ts>,v1=<hex>` where
    `v1 == HMAC-SHA256(secret, f"{t}.{raw_body}")`, computed over the EXACT
    bytes that were sent -- re-serializing parsed JSON would sign different
    bytes than what actually crossed the wire. Raises
    WebhookVerificationError on any failure; returns None on success.
    """
    if not secret:
        raise WebhookVerificationError("no webhook secret configured to verify against")
    if not signature_header:
        raise WebhookVerificationError(f"missing {SIGNATURE_HEADER} header")

    timestamp, provided_digest = parse_signature_header(signature_header)

    current = now if now is not None else time.time()
    skew = abs(current - timestamp)
    if skew > tolerance_seconds:
        raise WebhookVerificationError(f"timestamp skew {skew:.0f}s exceeds the {tolerance_seconds}s window")

    signed_string = f"{timestamp}.".encode("utf-8") + raw_body
    expected_digest = hmac.new(secret.encode("utf-8"), signed_string, hashlib.sha256).hexdigest()

    if not hmac.compare_digest(expected_digest, provided_digest):
        raise WebhookVerificationError("signature mismatch")


def verify_agent_id(header_value: str | None, expected_agent_id: str) -> None:
    """`X-Salt-Agent-Id` must name THIS agent -- a process hosting one
    identity uses it as a sanity check that the webhook wasn't misrouted."""
    if not header_value:
        raise WebhookVerificationError(f"missing {AGENT_ID_HEADER} header")
    if str(header_value).lower() != str(expected_agent_id).lower():
        raise WebhookVerificationError(
            f"{AGENT_ID_HEADER} {header_value!r} does not match this agent ({expected_agent_id!r})"
        )


_PGP_MESSAGE_RE = re.compile(r"^-----BEGIN PGP MESSAGE")


def classify(body: dict[str, Any]) -> EventType:
    """Which of the six webhook event families a parsed body belongs to.
    Matches salt-agent-sdk's dispatch() in webhook.ts: an explicit `type`
    field when present (typed events), else shape-sniffed for the message
    event, which carries no `type` at all."""
    explicit = body.get("type")
    if explicit in ("card_interaction", "invoice_paid", "chat_opened", "handoff_confirmed", "handoff_received"):
        return explicit
    if isinstance(body.get("message"), dict):
        return "message"
    # Shape-sniff, for a body that omits `type` but still matches one shape.
    if "action_id" in body and "card_id" in body:
        return "card_interaction"
    if "opened_by" in body:
        return "chat_opened"
    if "from_agent_id" in body:
        return "handoff_confirmed"
    if "to_agent_id" in body:
        return "handoff_received"
    if "line_items" in body or "buyer" in body:
        return "invoice_paid"
    return "unknown"


@dataclass
class Event:
    """A parsed, (optionally) signature-verified webhook/socket-update
    delivery -- the same shape whichever transport it arrived over."""

    type: EventType
    body: dict[str, Any]
    headers: dict[str, str] = field(default_factory=dict)
    delivery_id: str | None = None
    agent_id: str | None = None
    created_at: str | None = None


def handle(
    headers: Mapping[str, Any],
    raw_body: bytes | str,
    *,
    secret: str | None = None,
    verify: bool = True,
    tolerance_seconds: int = DEFAULT_TOLERANCE_SECONDS,
    now: float | None = None,
) -> Event:
    """Framework-neutral webhook entry point: headers + the exact raw body
    salt-api sent, in; a parsed Event out. Raises WebhookVerificationError
    if `verify` is true and the signature doesn't check out -- callers
    should treat that as a 401, never dispatch the body.

    `secret` is this identity's webhook signing secret (see
    `SaltClient.get_webhook_secret`); pass `verify=False` only against a
    local dev salt-api that doesn't sign at all.
    """
    if isinstance(raw_body, str):
        raw_bytes = raw_body.encode("utf-8")
    else:
        raw_bytes = raw_body

    agent_id = _get_header(headers, AGENT_ID_HEADER)
    signature = _get_header(headers, SIGNATURE_HEADER)
    delivery_id = _get_header(headers, DELIVERY_ID_HEADER)

    if verify:
        verify_signature(raw_bytes, signature, secret, tolerance_seconds=tolerance_seconds, now=now)

    try:
        body = json.loads(raw_bytes.decode("utf-8")) if raw_bytes else {}
    except (ValueError, UnicodeDecodeError) as exc:
        raise WebhookVerificationError(f"body is not valid JSON: {exc}") from exc

    return Event(
        type=classify(body),
        body=body,
        headers={str(k): str(v) for k, v in dict(headers).items()},
        delivery_id=str(delivery_id) if delivery_id is not None else None,
        agent_id=str(agent_id) if agent_id is not None else None,
    )


def create_asgi_app(
    dispatch: Any,
    *,
    verify_signatures: bool = True,
    secret: str | None = None,
    tolerance_seconds: int = DEFAULT_TOLERANCE_SECONDS,
    health_extra: dict[str, Any] | None = None,
) -> Any:
    """A minimal, dependency-free ASGI3 app: `POST /` verifies + parses the
    request into an Event and awaits `dispatch(event)`; `GET /health`
    answers a static status. No framework required -- run it directly
    under uvicorn/hypercorn, or mount it inside a bigger ASGI app.

    `dispatch` is an async callable taking one Event. Verification failures
    respond 401 without ever calling `dispatch` -- unsigned
    card_interaction/invoice_paid/chat_opened payloads are plaintext and
    actionable, so they must never reach dispatch unverified.
    """

    async def app(scope: dict[str, Any], receive: Any, send: Any) -> None:
        if scope["type"] == "lifespan":
            while True:
                message = await receive()
                if message["type"] == "lifespan.startup":
                    await send({"type": "lifespan.startup.complete"})
                elif message["type"] == "lifespan.shutdown":
                    await send({"type": "lifespan.shutdown.complete"})
                    return
            return

        if scope["type"] != "http":
            return

        method = scope["method"]
        path = scope.get("path", "/")
        headers = {k.decode("latin-1"): v.decode("latin-1") for k, v in scope.get("headers", [])}

        async def respond(status: int, payload: dict[str, Any]) -> None:
            body = json.dumps(payload).encode("utf-8")
            await send({
                "type": "http.response.start",
                "status": status,
                "headers": [[b"content-type", b"application/json"]],
            })
            await send({"type": "http.response.body", "body": body})

        if method == "GET" and path == "/health":
            await respond(200, {"status": "ok", **(health_extra or {})})
            return

        if method == "POST" and path in ("/", ""):
            body = b""
            more_body = True
            while more_body:
                message = await receive()
                body += message.get("body", b"")
                more_body = message.get("more_body", False)
            try:
                event = handle(headers, body, secret=secret, verify=verify_signatures, tolerance_seconds=tolerance_seconds)
            except WebhookVerificationError as exc:
                await respond(401, {"error": str(exc)})
                return
            # Ack immediately (200), then process -- a slow agent-loop call
            # must never make salt-api's webhook delivery time out. Any
            # dispatch failure is logged, never raised into the ASGI
            # server after the response has already been sent.
            await respond(200, {"status": "accepted"})
            try:
                await dispatch(event)
            except Exception as exc:  # noqa: BLE001
                _logger.error("[webhook] dispatch failed: %s", exc)
            return

        await respond(404, {"error": "not found"})

    return app
